server:
 port: 8089

management:
 security:
  enabled: false #关掉安全认证
 endpoints:
  shutdown:
   enabled: true #是否可通过endpoints关停应用服务
  web:
    base-path: /monitor
    exposure:
      include: '*'
 endpoint:
   health:
     show-details: always

info:
 app:
  name: spring-cloud-base